add functionality for user and item
ir0nmand0/java-shareit pull request #1
Opened 2024-07-01 11:48 UTC by ir0nmand0

Привет, после группового [проекта](https://github.com/Artem-lvv/java-shareit) подсмотрел несколько интересных фич в коде, по сравнению со своим прошлым проектом, но к DTO все равно специфическое отношение, так как по факту перекладывание «яиц из одной корзины в другую» с одной стороны это упрощает, но с другой стороны насколько быстро забьется ОЗУ в высоконагруженном проекте… Хотя я думаю для какого-то супер специфического сервиса эта работа будет переложена на rust или c++…

2024-07-01 18:26 UTC, EugeneLenkevich commented
> Привет, после группового [проекта](https://github.com/Artem-lvv/java-shareit) подсмотрел несколько интересных фич в коде, по сравнению со своим прошлым проектом, но к DTO все равно специфическое отношение, так как по факту перекладывание «яиц из одной корзины в другую» с одной стороны это упрощает,

Какой то оверхэд конечно же DTO привносят, однако они дают гибкость. Допустим у нас есть сервис в сложной ит-системе к которому другие сервисы обращаются по http. У него есть некоторый контракт - это как раз интерфейсы и dto, которые торчат наружу и которые используют другие сервисы. Таким образом используя dto мы можем

1. абстрагироваться от внутренней структуры сервиса и выдавать какую то более простую картинку в виде DTO. Допустим у нас есть платежи, мы отдаем их сумму как баланс счета и не всю пачку счетов чтобы сторонний сервис сам все это считал, а он бы был вынужден считать если бы в контракт выкатывали всю модель данных как есть
2. мы можем поменять внутри нашу модель данных, но сохранить контракт и таким образом другие сервисы без проблем будут работать ка ки раньше
3. если же мы вынуждены поменять контракт то мы можем иметь несколько версий контракта, так мы обеспечим обратную совместимость и безперебойность работы нашей ит-системы 

>  но с другой стороны насколько быстро забьется ОЗУ в высоконагруженном проекте…

 Они почти сразу поступают на сборку мусора, так что, если не накосячить, то проблем с ОЗУ не будет. А если накосячить.. ну тут без разницы какими объектами память прееполнять)


> Хотя я думаю для какого-то супер специфического сервиса эта работа будет переложена на rust или c++…

На самом деле добавляют еще несколько виртуалок в кластер :D
Достаточно сравнить стоимость новой железяки и стоимость работы команды. Хотя,  в каких то особенных случаях могут и на C++ что то реализовать, в случае микросервисов это достаточно просто делается, но опять таки там все равно скорее всего будут dto - в контракте.  :)
Вообще, по опыту, тормозить скорее всего будет ввод/вывод: сеть, диск, СУБД и пр

2024-07-01 18:29 UTC, EugeneLenkevich requested changes
Привет, Дмитрий! Спасибо за PR.
 
Так, давай попробуем почистить код от @Qualifier, не надо его так часто использовать, скорее всего и без него все работает 
Далее, про Optional, есть места где можно сократить код используя метод orElseThrow, посмотри комментарии, пожалуйста

А так, в целом, отличная работа :)

2024-07-01 18:29 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    @Qualifier("userServiceImpl")
В принципе если бины(реализации) присутствуют в единичной экземпляре, что  @Qualifier и не надо писать, лучше без него обойтись, это лишняя техническая информация которая особо никому не интересна. А если бинов несколько то будет падать ошибка что реализаций несколько, тогда можно на один из них поместить аннотацию @Primary и он будет подхватываться по умолчанию :)

2024-07-01 18:29 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (user.isEmpty()) {
Можно покороче записать :) 

return userStorage.findById(id). orElseThrow(->{
String message = "User not found by id " + id;
 log.warn(message);
 throw new EntityNotFoundByIdException("User", message);
})

2024-07-01 18:29 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (item.isEmpty()) {
Покороче можно записать, используя orElseThrow :)

https://struchkov.dev/blog/ru/optional-in-java/

2024-07-03 12:30 UTC, ir0nmand0 commented
> > Привет, после группового [проекта](https://github.com/Artem-lvv/java-shareit) подсмотрел несколько интересных фич в коде, по сравнению со своим прошлым проектом, но к DTO все равно специфическое отношение, так как по факту перекладывание «яиц из одной корзины в другую» с одной стороны это упрощает,
> 
> Какой то оверхэд конечно же DTO привносят, однако они дают гибкость. Допустим у нас есть сервис в сложной ит-системе к которому другие сервисы обращаются по http. У него есть некоторый контракт - это как раз интерфейсы и dto, которые торчат наружу и которые используют другие сервисы. Таким образом используя dto мы можем
> 
> 1. абстрагироваться от внутренней структуры сервиса и выдавать какую то более простую картинку в виде DTO. Допустим у нас есть платежи, мы отдаем их сумму как баланс счета и не всю пачку счетов чтобы сторонний сервис сам все это считал, а он бы был вынужден считать если бы в контракт выкатывали всю модель данных как есть
> 2. мы можем поменять внутри нашу модель данных, но сохранить контракт и таким образом другие сервисы без проблем будут работать ка ки раньше
> 3. если же мы вынуждены поменять контракт то мы можем иметь несколько версий контракта, так мы обеспечим обратную совместимость и безперебойность работы нашей ит-системы
> 
> > но с другой стороны насколько быстро забьется ОЗУ в высоконагруженном проекте…
> 
> Они почти сразу поступают на сборку мусора, так что, если не накосячить, то проблем с ОЗУ не будет. А если накосячить.. ну тут без разницы какими объектами память прееполнять)
> 
> > Хотя я думаю для какого-то супер специфического сервиса эта работа будет переложена на rust или c++…
> 
> На самом деле добавляют еще несколько виртуалок в кластер :D Достаточно сравнить стоимость новой железяки и стоимость работы команды. Хотя, в каких то особенных случаях могут и на C++ что то реализовать, в случае микросервисов это достаточно просто делается, но опять таки там все равно скорее всего будут dto - в контракте. :) Вообще, по опыту, тормозить скорее всего будет ввод/вывод: сеть, диск, СУБД и пр

Спасибо за ответ, я так понял не всегда получится обойтись этим:  [@JsonIgnore](https://www.baeldung.com/jackson-annotations) или иными подобными решениями...

2024-07-03 17:30 UTC, EugeneLenkevich commented
> Спасибо за ответ, я так понял не всегда получится обойтись этим: [@JsonIgnore](https://www.baeldung.com/jackson-annotations) или иными подобными решениями...

Не всегда, все верно, и чем больше проект тем больше бывает надо пилить дополнительных слоев, слышал небось фразу "json-ы перекладывать" - так это про написание интеграций для разных систем, обычная работа в ИТ отделе банка)
Но в мелких проектах часто без этого всего обходятся, там уже это часто лишнее, проще сразу сущность отдать в контроллер, часто даже без сервиса, но тут тоже свои особенности, серебряной пули нет

2024-07-03 17:31 UTC, EugeneLenkevich approved these changes
То что надо, спасибо :)

2024-07-03 18:58 UTC, merged