add implementation: booking and comment
ir0nmand0/java-shareit pull request #2
Opened 2024-07-29 21:42 UTC by ir0nmand0

Приветствую, это была насыщенная тема с транзакциями и hibernate, попытался максимально освоить эту библиотеку на сколько это было возможно, поэтому в репозиториях могут быть дубликаты запросов к БД (делают одно и тоже): были реализованы при помощи наименования метода, а где-то писал вручную запрос. Только после изучения всего этого, вопросов появилось еще больше, особенно стал интересоваться асинхронным доступом к БД. Пока, что для меня тайна для чего нужно это: saveAndFlush и @Modifying(clearAutomatically = true, flushAutomatically = true), в документации нашел описание, но вот зачем и как использовать это на практике особо не понял…

2024-07-30 08:31 UTC, EugeneLenkevich commented
> saveAndFlush
Хибер не сразу сохраняет все изменения в БД, а хранит их в собственном кэше. В рамках текущей транзакции, конечно. Плюс у него есть кэш для сущностей. Сделано это для оптимизации, там внутри своя магия. Вызывая flush мы по сути дела синхронизируем кэши и БД. 
И таки да, тема сложная и тут граблей насыпано будь здоров. Это и уровни изоляций для транзакций и оптимистические и пессимистические локи. Это то что касается многопоточного доступа. 

https://habr.com/ru/articles/135176/

2024-07-30 08:33 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/converter/BookingToBookingDtoConverter.java
> +                .item(ItemIdAndNameDto.builder()
Для вложенных объектов можно отдельные мапперы сделать и инжектить тут. Вдруг потом еще где то потребуются

2024-07-30 08:49 UTC, EugeneLenkevich requested changes
Привет, Дмитрий! Спасибо за PR.

Все верно, я бы даже сказал работа впечатляет :)
Один момент - сама суть ORM в том, чтобы уйти в объектную парадигму по максимуму, а когда мы пишем апдейты руками  мы возвращаемся к реляционной модели и тем самым усложняем себе жизнь. Попробуй обойтись без такого количества апдейтов (только если на крайний случай), лучше работать с объектами: достать сущность, засетить данные, сохранить
Ну имена методов у репозиториев - если слишком длинный метод и его становится трудно читать, то лучше сократить и написать запрос через query :)

2024-07-30 08:49 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/database/BookingRepository.java
> +    Optional<Booking> findOneByIdAndBookerIdOrItemUserId(final long id, final long userId);
findOneByIdAndBookerIdOrItemUserId

Если мы задачем запрос вручную то имя метода можно и покороче сделать, чтобы удобно было. Вообще, если метод репозитория становится неудобным и слишком длинным, то лучше через query запрос руками написать, потому будет проще такой код читать :)

2024-07-30 08:49 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/database/BookingRepository.java
> +    void updateStartAndEnd(@Param("start") final LocalDateTime start,
А надо ли нам столько апдейтов, иногда проще получить сущность, положить в нее через сет-метод данные и сохранить и обойтись без самих запросов. Так же ошибиться очень просто, надо тогда тщательно тестами покрывать, которые проверяют что мы обновляем только нужную запись :)

2024-07-30 08:49 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
Ну вот тут какие сложности с этими методами, было бы проще если бы мы просто у сущности вызывали нужные set-методы и в конце сохраняли, хибер бы нам сам сгенерировал нужный апдейт :)

2024-07-30 08:49 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/storage/database/ItemRepository.java
> +    Collection<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(final String name,
Хороший пример метода который лучше описать через query :)

2024-07-30 08:49 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/storage/database/CommentRepository.java
> +            + "left join fetch Booking lb on lb.item.id = i.id and lb.end = (select max(b.end) "
Суровые конечно запросы, но да, лучше на уровне СУБД запросом нужные данные отбирать, это правильно :)

2024-07-30 09:04 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
А, еще момент с апдейтами.
Допустим у нас есть сущность А, открыта транзакция, мы с ней работает, запускаем по ней апдейт через метод репозитория(именно чтобы был он в рамках той же транзакции), на уровне СУБД данные обновятся а вот кэши - нет, можешь проверить что будет :)

вот как то так, можешь в тесте погонять

@Transactional
void a() {
Booking b = get(id)
repo.updateStartAndEnd(...)
repo.save(b);
}


Как раз тот момент когда абстракции протекают

2024-07-30 10:54 UTC, ir0nmand0 commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
А если сделать так?  @Modifying(clearAutomatically = true, flushAutomatically = true), ну я понимаю, что лучше использовать различные готовые save, но цель была по максимуму разобраться=)

2024-07-30 11:01 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
Тут надо руками щупать, можно в тесте, например как выше, воспроизвести ситуацию, попереставлять флаги и посмотреть что будет, можно еще show_sql=true если не стоит выставить и смотреть какие и когда запросы в реальности происходят

2024-07-30 19:58 UTC, ir0nmand0 commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
Запустил проект с подправленным конфигом, взял [отсюда](baeldung.com/sql-logging-spring-boot), увидел, что сущности при таком подходе в кеше не обновляются, нормально работает только через save, но если добавить (clearAutomatically = true, flushAutomatically = true), тогда кэш вычищается корректно и при следующем селекте будет загружено в кэш из БД как надо. Пока еще Мок тестирование не прошел, но думаю, как раз при детальных тестах каждого метода получиться увидеть нагляднее..

2024-07-30 19:59 UTC, ir0nmand0 commented on src/main/java/ru/practicum/shareit/booking/storage/database/BookingRepository.java
> +    void updateStartAndEnd(@Param("start") final LocalDateTime start,
Это больше ознакомительная цель была, я изначально использовал просто save=)

2024-07-30 20:13 UTC, ir0nmand0 commented on src/main/java/ru/practicum/shareit/item/storage/database/ItemRepository.java
> +    Collection<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(final String name,
Сделал:
`@Query("select i from Item i where (i.name ilike :text or i.description ilike :text) and i.available is true")
 Collection<Item> findAllByText(final String text);`

2024-07-30 20:43 UTC, ir0nmand0 commented on src/main/java/ru/practicum/shareit/booking/converter/BookingToBookingDtoConverter.java
> +                .item(ItemIdAndNameDto.builder()
Реализовал.

2024-07-31 03:17 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
Ну собственно вот, так хибер после каждого запроса сбрасывает состояние, но надо понимать что это влияет и на его внутренние оптимизации и больше похоже на хак, но, за то, вон сколько всего раскопали :)

2024-07-31 03:17 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-07-31 10:45 UTC, merged

2024-08-03 07:27 UTC, ir0nmand0 commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
https://habr.com/ru/articles/833478/ вышла новая статья, теперь больше понимания по этому вопросу.

2024-08-03 14:54 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/storage/database/InDbBookingStorage.java
> +        if (!startIsEmpty && !endIsEmpty && !statusIsEmpty) {
Ну да. все верно, по первичному ключу, а статья гут, спасибо :)