add item request, gateway and tests
ir0nmand0/java-shareit pull request #3
Opened 2024-08-08 22:18 UTC by ir0nmand0

2024-08-09 15:50 UTC, EugeneLenkevich requested changes
Привет, Дмитрий, спасибо за ПР

Ну, добро пожаловать в еще более необъятный мир - мир распределенной архитектуры, микросервисов и пр. чертовщины и головной боли с распределенным состоянием :D

Но, у нас плюшевое задание, в принципе ровно на столько чтобы увидеть как микросервисы работают. Просят валидацию на сервере почикать плюс ля примера предложу вэб-клент в конфигурацию оформить, но это все по желанию

2024-08-09 15:50 UTC, EugeneLenkevich commented on server/src/main/java/ru/practicum/shareit/request/model/dto/CreateItemRequestDto.java
> +        @NotBlank
По ТЗ просят убрать всю валидацию из контроллеров модуля server, давай ее уберем (все что не требует запросов в БД, т.е. аннотации),  с dto в том числе.  (Но вот на сущностях пусть остается, но, в принципе, она может отличаться в зависимости от бизнес-логики)

 С одной стороны кажется немного странным такое требование, но в этом есть своя логика: не дублировать проверки ибо, в будущем, проверки придется править в разных местах и рано или поздно это приведет к рассинхронизации реализаций и появлению множества багов, как следствие. А в микросервисах починка багов - это то еще приключение :)

PS
Иногда вообще как делают. Микросервис разбивают на два модуля: реализация и контракты (все dto и пр интерфейсы). Другой микросервис (в нашем случае это gateway), который хочет обратится к нашему сервису, импортирует наши контракты и с помощью них и строит запросы. Так обеспечивается соответствие API.
В контракты так же может быть помещен и web-клиент со всем настройками, соответственно, импортируем контракты, инжектим бин клиента, вызываем методы клиента, все остальное от нас сокрыто, не надо возится с настройками и API, в теории, всегда у нас соответствует :)

2024-08-09 15:50 UTC, EugeneLenkevich commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                        .uriTemplateHandler(new DefaultUriBuilderFactory(serverUrl + API_PREFIX))
Вот тут есть моментик, который можно улучшить :)
 
В самом клиенте происходит создание и настройка web-клинента. С архитектурной точки зрения это не очень хорошо, клиент занимается своей настройкой, это не его обязаность. Настройку лучше вынести вовне. Можно сделать конфигурацию для бина web-clients и далее он, настроенный, будет инжектится как и остальные бины.

Единственное, аннотацию @Service надо убрать, вообще, это алтернативный способ объявления бинов: мы можем на класс повесить аннотацию или создать такую вот конфигурацию если требуется провести какую то настройку при создании 

Пример вот, только подправь под свою реализацию

![image](https://user-images.githubusercontent.com/94845100/193436606-1894b4f9-aa6d-4359-adec-0791cef7a4e6.png)


Таким образом мы можем иметь разные настройки клиентов для разных сред: допустим на продакшн-сервере с TLS, сертификатами и пр, на тестововм стенде простое соединение, а для локального запуска мы можем, например, вообще создать заглушку, которая будет возвращать статический текст :)


https://www.baeldung.com/spring-profiles

2024-08-09 18:11 UTC, ir0nmand0 commented on server/src/main/java/ru/practicum/shareit/request/model/dto/CreateItemRequestDto.java
> +        @NotBlank
Я в теории так и сделал, просто убрал @Valid,  но так же удалил дополнительные проверки.

2024-08-09 18:19 UTC, ir0nmand0 commented on server/src/main/java/ru/practicum/shareit/request/model/dto/CreateItemRequestDto.java
> +        @NotBlank
> Иногда вообще как делают. Микросервис разбивают на два модуля: реализация и контракты (все dto и пр интерфейсы). Другой микросервис (в нашем случае это gateway), который хочет обратится к нашему сервису, импортирует наши контракты и с помощью них и строит запросы.

Следующее ТЗ, как раз именно так и нужно сделать, у меня не дипломный, а ГП.

2024-08-09 19:38 UTC, ir0nmand0 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +                        .uriTemplateHandler(new DefaultUriBuilderFactory(serverUrl + API_PREFIX))
[Сделал](https://github.com/ir0nmand0/java-shareit/pull/3/commits/097f400fcb786806f2aad6a004d61c13ed834d12), надеюсь суть уловил

2024-08-10 03:06 UTC, EugeneLenkevich requested changes
Да, все верно ты основную идею уловил, по сути дела это альтернативный способ создания бинов, аналогичный расставлению аннотаций @Component, но мы еще можем сделать удобным способом некоторые манипуляции при инициализации :)

2024-08-10 03:06 UTC, EugeneLenkevich commented on gateway/src/main/java/ru/practicum/shareit/config/WebClientConfig.java
> +                .requestFactory(() -> new HttpComponentsClientHttpRequestFactory())
new HttpComponentsClientHttpRequestFactory()

Как минимимум вот эту штуку можно было сделать бином, чтобы не копипастить несколько раз. В целом, правда, без особой разницы, больше чтобы показать сам подход :)

2024-08-10 10:05 UTC, ir0nmand0 commented on gateway/src/main/java/ru/practicum/shareit/config/WebClientConfig.java
> +                .requestFactory(() -> new HttpComponentsClientHttpRequestFactory())
Поправил =)

2024-08-10 10:12 UTC, merged